import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--font-geist-sans',
   weight: '100 900',
});
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--font-geist-mono',
   weight: '100 900',
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}
         >
            <header className='flex items-center pl-8 w-full h-12 bg-blue-400 '>
               <h2 className='text-2xl text-white font-bold'>Header</h2>
            </header>
            <main className='min-h-[80vh]'>{children}</main>
            <footer className='flex items-center pl-8 w-full h-12 bg-orange-200 '>
               <h2 className='text-2xl text-slate-900 font-bold'>Footer</h2>
            </footer>
         </body>
      </html>
   );
}
